name: 'Lerna Changed'
description: 'Github action for determining the changed packages in a lerna monorepo'
author: 'Allen Evans'
inputs:
  cwd:
    description: 'Current working directory'
    default: ''
    required: false
  include:
    description: 'Include existing packages into the list of changed packages'
    default: ''
    required: false
outputs:
  scope:
    description: 'Value containing the changed package scope, or empty string if no changes present'
runs:
  using: 'node12'
  main: 'dist/lerna-changed.js'
