name: 'lerna-changed'
description: 'Github action for determining the changed packages in a lerna monorepo'
author: 'Allen Evans'
inputs:
  cwd:
    description: 'Current working directory'
    default: ''
  envVar:
    description: 'Set the environment variable with the changed packages output'
    default: ''
runs:
  using: 'node12'
  main: 'lib/main.js'
