name: "Build pipeline"
on: [push]

jobs:
  validation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: "Config"
        run: |
          git config --global user.email "git-ci@techinity.com"
          git config --global user.name "gitci"

      - name: "Install dependencies"
        run: npm install

      - name: "Build"
        run: npm run build

      - name: "Test"
        run: npm run test

      - name: "Lint"
        run: npm run lint

      - name: "Check for uncommitted changes"
        run: |
          git diff --exit-code --stat -- . ':!node_modules' \
          || (echo "##[error] found changed files after build." \
              && exit 1)

      - name: "Commit build artifacts"
        if: github.ref == 'refs/heads/master' && github.actor != 'gitci'
        run: |
          git add -f dist/
          git commit -m 'release artifacts'

      - name: "Semantic version"
        if: github.ref == 'refs/heads/master' && github.actor != 'gitci'
        env:
          GH_TOKEN: ${{secrets.GITHUB_ACTION_TOKEN}}
        run: |
          npx semantic-release --branch master
